Repository iipeace/guider, pull requests merged in 2020-10, with the labels that each got.

#231 doc: Update README.md
  README.md
  guider/guider.py
Labels: Hacktoberfest, SOSFest

#232 btrace: Fix arg value 0 issues
  guider/guider.py
Labels: Hacktoberfest, SOSFest

#236 event: Add socket address cache for Guider processes
  guider/guider.py
Labels: Hacktoberfest, SOSFest

#237 strace: Add list option
  guider/guider.py
Labels: Hacktoberfest, SOSFest

#239 docs: LICENSE document addition and various text changes
  manager/admin-web/LICENSE
  manager/admin-web/README.md
  manager/admin-web/package.json
  manager/admin-web/src/localization/strings.js
Labels: Hacktoberfest, SOSFest

#241 feat: Change state values ​​and resources to suit deep purple theme
  manager/admin-web/.gitignore
  manager/admin-web/public/favicon.ico
  manager/admin-web/public/images/errors/error-401.png
  manager/admin-web/public/images/errors/error-404.png
  manager/admin-web/public/images/errors/error-500.png
  manager/admin-web/public/images/logos/logo-guider.png
  manager/admin-web/src/layouts/Auth/TopBar.js
  manager/admin-web/src/layouts/Dashboard/TopBar.js
  manager/admin-web/src/theme/palette.js
Labels: Hacktoberfest, SOSFest

#242 doc: Update README.md
  README.md
  guider/guider.py
Labels: SOSFest, hacktoberfest

#243 btrace: Fix various command bugs
  guider/guider.py
Labels: SOSFest, hacktoberfest

#244 btrace: Add CMD field for getret command
  guider/guider.py
Labels: SOSFest, hacktoberfest-accepted

#245 btrace: Add CMD field for setret command
  guider/guider.py
  utils/reindent.py
Labels: SOSFest, hacktoberfest-accepted

#247 Add commands and args for btrace and strace
  guider/guider.py
Labels: SOSFest, hacktoberfest-accepted

#248 ImplAnalyzer: Support glob pattern for path
  guider/guider.py
  utils/ImplAnalyzer/ImplAnalyzer.py
Labels: SOSFest, hacktoberfest-accepted

#249 ElfAnalyzer: Add DWARF CIE parser
  guider/guider.py
Labels: SOSFest, hacktoberfest-accepted, python

#251 option: Add generalInfo option
  guider/guider.py
Labels: SOSFest, hacktoberfest-accepted

#252 ElfAnalyzer: Add DWARF CIE parser
  guider/guider.py
Labels: SOSFest, hacktoberfest-accepted

#253 ElfAnalyzer: Add DWARF CONSTANTS
  guider/guider.py
Labels: enhancement
